### ISSUE TITLE
[B31] Stage 2 콜라이더 인식 오류

### ISSUE THREAD

**Issue by YongHyeon02** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-05#105]
## 이름
Stage 2 콜라이더 인식 오류

## 설명
Stage 2 의 낙하 블럭 콜라이더가 가끔 인식이 안됨.

## 재현 방법
1. 재현 방법은 아직 찾지 못함.

**Comment by paul159357** [comment]
b33과 같은 이슈입니다.
