### ISSUE TITLE
[B39] 배경 어둡게 하기

### ISSUE THREAD

**Issue by paul159357** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-05#118]
## 이름
모든 씬의 배경이 밝고 밀도가 높아서, 근경의 게임이 잘 보이지 않습니다.

## 설명
SpriteRenderer 색상을 모두 어둡게 조정하고, Terrain 등 3d 배경은 크기를 키운 후 Z축으로 멀리 떨어뜨린 뒤 fog를 적용해서 무채색 계열로 덮어주세요. Lighting/Environment에서 fog 켜고 linear 모드 설정 뒤 색상이랑 적용 범위 조정하시면 됩니당. 다른 방법으로 배경만 어둡게 할 수 있어도 좋아여.
ex.
![image](https://github.com/user-attachments/assets/f8724a01-a185-458f-b719-f26540db0900)
![image](https://github.com/user-attachments/assets/d5b801d3-070a-4b0b-8e79-e037740e604c)

**Comment by seung-wook-0111** [comment]
Recent commit to art branch resolved the issue
