### ISSUE TITLE
[B11] 액션 104인 상태에서 Jump 조건 확인 이슈

### ISSUE THREAD

**Issue by YongHyeon02** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-05#57]
## 이름
액션 104인 상태에서 Jump 조건 확인 이슈

## 설명
JumpValid 조건확인 후 현재 액션이 104인 상태에서 Jump 조건 확인이 발생하는지 확인하였음.
이 결과 (1, 참) (1, 거짓) 번갈아 가면서 나타남.

## 재현 방법
ActionModule에서 
case eActionCondition.Jump: 
    if(Input.GetKey(KeyCode.X)) cond_val = 1;
    else cond_val = 0;
    Debug.LogWarning($"[CheckCondition] Jump 조건 평가: cond_val = {cond_val} (val = {val})");
다음과 같이 수정 후 실행 시 발생

**Comment by paul159357** [comment]
TC 작성 단계에서의 오류였습니다.
