### ISSUE TITLE
[B27] 점프에 따라 활성/비활성 블록 X키 무한 활성/비활성 버그

### ISSUE THREAD

**Issue by YongHyeon02** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-05#94]
## 이름
점프에 따라 활성/비활성 블록 X키 무한 활성/비활성 버그

## 설명
점프에 따라 활성/비활성 되는 블럭(이하 점프 블럭)이 X키를 누를 때마다 활성/비활성화 되는 상황이 존재함.

## 재현 방법
1. Stage_3_1 진입
2. 플레이어가 점프하여 점프 블럭 위로 올라감
3. 점프 블럭 위에서 X키 연타하면 점프 블럭 무한 활성/비활성화 됨.

**Comment by paul159357** [comment]
의심 원인 : transform module jump allowed 판정 쪽 collision exit에서 닿아 있던 ground collider를 리스트에서 빼주면서 jump allowed가 false가 되는 걸로 기억하는데, 이게 collider가 꺼지면 collsion exit이 안 불리는 거 같습니다. 아마 JumpAllowed getter에서 리스트 돌면서 enabled=false인 콜라이더가 있으면 리스트에서 빼주고 list.count == 0 retun하도록 하면 될 거에여
