### ISSUE TITLE
[B28] 레벨 디자인 콜라이더 이상

### ISSUE THREAD

**Issue by YongHyeon02** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-05#96]
## 이름
레벨 디자인 콜라이더 이상

## 설명
Stage_4_1의 콜라이더가 이상한 부분이 있음.

## 재현 방법
![image](https://github.com/user-attachments/assets/fe72dd8e-ea5d-4bee-85a9-fa2b130508ee)
해당 사진에서 플레이어가 바라보고 있는 벽 쪽이 콜라이더가 비어 있음.

## 추정 원인
해당 사진에서 플레이어가 바라보고 있는 벽 쪽이 콜라이더가 비어 있음.

## 권장 해결 방법
콜라이더 변경

**Comment by paul159357** [comment]
mountain cube 5번에 콜라이더 없어진 것 확인했읍니다. 다른 스테이지도 다 다시 로드 후 콜라이더 확인하고 올릴게여.
